config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'home', to: 'pages#home'

  get 'pages/about'
  get 'about', to: 'pages#about'

  # Todo: This static page is unnecessary.
  get 'pages/subscribe'
  get 'subscribe', to: 'pages#subscribe'

  resources :subscribers do
    get 'unsubscribe', on: :member
  end
  resources :posts do
    resources :comments
  end
  resources :users

  root 'pages#home'
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/subscriber.rb
class Subscriber < ApplicationRecord

  validates :name, presence: true

  # ToDo: Send mail with confirmation link.
  validates_format_of :email, :with => /@/, :message => "must contain an @ sign"
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Unsubscribe from email notifications.
  # This is essentially the same as destroy, but with a friendly message.
  def unsubscribe
    subscriber = Rails.application.message_verifier(:unsubscribe).verify(params[:id])
    @subscriber = Subscriber.find(subscriber)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:name, :email)
    end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_for(subscriber, :html => { :class => "form-inline" }) do |f| %>
  <% if subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control" %>
    <small class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>

  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
    <%= link_to "Cancel", subscribers_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

app/views/subscribers/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Subscribers</h1>

<p><small><%= link_to 'Add new subscriber', new_subscriber_path %></small></p>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.name %></td>
        <td><%= subscriber.email %></td>
        <td><%= link_to 'Show', subscriber %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/subscribers/new.html.erb
<h1>New Subscriber</h1>

<h2>Never miss a post!</h2>
<p>Fill out this form, and you will get sent an email informing you of every new post!</p>
<br>

<%= render 'form', subscriber: @subscriber %>

app/views/subscribers/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @subscriber.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @subscriber.email %>
</p>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/unsubscribe.html.erb
<h3>Unsubscribe from Paul's Lovely Rails Blog emails</h3>
<p>We'll be sad to see you go, <%= @subscriber.name %>.</p>
<p>By unsubscribing, you will no longer receive email notifications of new posts.</p>
<p>The system will forget you forever!</p>

<h3>Are you sure you want to unsubscribe?</h3>
<p><%= link_to 'Yes, please stop emailing me.', @subscriber, method: :delete %></p>
<p><%= link_to 'No, I clicked the unsub link accidentally and now I feel silly.', root_url %></p>