config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'home', to: 'pages#home'

  get 'pages/about'
  get 'about', to: 'pages#about'

  # Todo: This static page is unnecessary.
  get 'pages/subscribe'
  get 'subscribe', to: 'pages#subscribe'

  resources :subscribers do
    get 'unsubscribe', on: :member
  end
  resources :posts do
    resources :comments
  end
  resources :users

  root 'pages#home'
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true, length: { maximum: 140 }
  validates :body, presence: true

  def to_param
    [id, title.parameterize].join("-")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_markdown, only: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save

        # Sends email to all subscribers when new post is created.
        send_new_post_mail(@post.id)

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end

    # Set up the markdown parser.
    def set_markdown
      @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, extensions = {})
    end

    # Sends email to all subscribers when new post is created.
    def send_new_post_mail(post_id)
      Subscriber.all.each do |subscriber|
        NewPostMailer.send_to_one_subscriber(post_id, subscriber.id).deliver

        # ToDo: Test async mail on Heroku. Can't run the daemon on Windows.
        # NewPostMailer.send_to_one_subscriber(post_id, subscriber.id).deliver_later
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  # Display any edits as hover-over title text.
  # If the post has been edited, add an asterisk to the date.
  def get_date_display_text(post)
    output = {}

    if post.created_at === post.updated_at
      output[:value] = post.created_at.strftime("%Y/%m/%d at %H:%M")
      output[:title] = "No edits made"
    else
      output[:value] = post.created_at.strftime("%Y/%m/%d at %H:%M") + "*"
      output[:title] = "Last edited: #{post.updated_at.strftime("%Y/%m/%d %H:%M")}"
    end

    output
  end

end

app/views/posts/_form.html.erb
<script>
// Add markdown editor to the post body field.
$( document ).ready( function() {
  var elem = $("#field_body")[0]
  var simplemde = new SimpleMDE({ element: elem })
})
</script>

<%= form_for(post, :html => { :class => "form-inline" }) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, :class => "form-control", :id => "field_body" %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
    <%= link_to "Cancel", posts_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Posts</h1>

<p><small><%= link_to 'Create new post', new_post_path %></small></p>
<p><small><%= link_to 'Subscribe to this site', new_subscriber_path %></small></p>

<hr>

<% @posts.each do |post| %>
  <% date_text = get_date_display_text(post) %>

  <%# Show the post. %>
  <h2 class="postTitle"><%= link_to post.title, post %></h1>
  <div class="postUserAndDate">
    By <span class="userName"><%= post.user.name %></span>
    on <span class="postDate" title="<%= date_text[:title] %>"><%= date_text[:value] %></span>
  </div>
  <div class="postBody"><%= @markdown.render(post.body).html_safe %></div>

  <%# Show the action options. %>
  <div>
    <%= link_to 'Show', post %> |
    <%= link_to 'Edit', edit_post_path(post) %> |
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  <hr>
<% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<% date_text = get_date_display_text(@post) %>

<%# Show the post. %>
<h1 class="postTitle"><%= @post.title %></h1>
<div class="postUserAndDate">
  By <span class="userName"><%= @post.user.name %></span>
  on <span class="postDate" title="<%= date_text[:title] %>"><%= date_text[:value] %></span>
</div>
<div class="postBody"><%= @markdown.render(@post.body).html_safe %></div>

<%# Show the footer nav. %>
<nav id="postFooterNav">
  <%= link_to 'Back to posts', posts_path %>
  <%= link_to 'Edit this post', edit_post_path(@post) %>
</nav>

<%# Show the comments. %>
<div class="comments">
  <h2>Comments</h2>

  <% @post.comments.each do |comment| %>
    <%# If the comment errored, there will be no 'created_at' %>
    <%# This smells pretty bad, but it seems to work. %>
    <% if comment.created_at %>
      <p>
        <div>
          <strong><%= comment.name %></strong>
        </div>
        <div>
          <%= comment.created_at.strftime("%Y/%m/%d %H:%M") %>
        </div>
        <div>
          <%= comment.body %>
        </div>
      </p>
    <% end %>
  <% end %>

  <% if @post.comments.empty? %>
    <p>
      <div>
        There are no comments for this post.
      </div>
    </p>
  <% end %>
</div>

<hr>

<%# If we are editing an errored comment, remember the previous value. %>
<%# This will be used as the default value for the form fields. %>
<% if @comment %>
  <% name_value = @comment.name %>
  <% body_value = @comment.body %>
<% end %>

<h2>Add comment</h2>

<%= form_for([@post, @post.comments.build]) do |f| %>

  <% if @comment && @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# Default values are okay to be nil. %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control", value: name_value %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, :class => "form-control", value: body_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>