config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'home', to: 'pages#home'

  get 'pages/about'
  get 'about', to: 'pages#about'

  # Todo: This static page is unnecessary.
  get 'pages/subscribe'
  get 'subscribe', to: 'pages#subscribe'

  resources :subscribers do
    get 'unsubscribe', on: :member
  end
  resources :posts do
    resources :comments
  end
  resources :users

  root 'pages#home'
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Paul's Lovely Rails Blog", root_path %>
    by <a href="https://github.com/nossidge/">Paul Thompson</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", {:controller => 'pages', :action => 'about'} %></li>
      <li><%= mail_to 'pauldpthompson@gmail.com', "Contact" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Paul's Lovely Rails Blog", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",        root_path %>
        <li><%= link_to "Users",       users_path %></li>
        <li><%= link_to "Posts",       posts_path %></li>
        <li><%= link_to "Subscribers", subscribers_path %></li>
        <li><%= link_to "About",       about_path  %></li>
        <li><%= link_to "Log in",      '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>